version: 2.1

jobs:
  build:

    macos:
      xcode: 12.4.0

    steps:
      - checkout
      - run: 
        command: fastlane scan
        environment:
          SCAN_DEVICE: iPhone 11
          SCAN_SCHEME: AsteroidWatchAPI

      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output
          
    workflows:
      build-and-test:
        jobs:
          - build-and-test
© 2021 GitHub, Inc.
